<a href="https://colab.research.google.com/github/abdulsamadkhan/MachineLearningTutorials/blob/main/Introduction%20to%20pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro to Dataframes
Pandas is a powerful library in Python for data manipulation and analysis, especially for working with tabular data.

In [3]:
import pandas as pd
import numpy as np

A DataFrame is a 2D table-like data structure with rows and columns.

In [9]:
# Creating a simple DataFrame
# Explanation: A DataFrame is a 2D table with rows and columns, similar to an Excel sheet.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 47, 19],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)

# Displaying the DataFrame
# Explanation: This prints the DataFrame to view its contents
df

      Name  Age         City
0    Alice   25     New York
1      Bob   32  Los Angeles
2  Charlie   47      Chicago
3    David   19      Houston

In [11]:
# Create a DataFrame with the given data, column names, and row indices
df = pd.DataFrame(
    [
        [1, 2, 3],  # Row 1 data
        [4, 5, 6],  # Row 2 data
        [7, 8, 9],  # Row 3 data
        [10, 11, 12]  # Row 4 data
    ],
    columns=["A", "B", "C"],  # Assign column names
    index=["x", "y", "z", "zz"]  # Assign row indices
)

In [12]:
# Print the first 5 rows of the DataFrame
print(df.head())

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [13]:
# Select the 'A' column from the DataFrame
column_A = df['A']

# Print the selected column
print(column_A)
#The return type of df['A'] is a pandas Series.

#A pandas Series is a one-dimensional labeled array-like object that can hold any data type (integers, floats, strings, etc.).
print(type(column_A))

x      1
y      4
z      7
zz    10
Name: A, dtype: int64
<class 'pandas.core.series.Series'>

In [14]:
# Select the multiple columns from the DataFrame
df[['A','B']]

     A   B
x    1   2
y    4   5
z    7   8
zz  10  11

In [15]:
# Print the last 2 rows of the DataFrame
print(df.tail(2))

     A   B   C
z    7   8   9
zz  10  11  12

In [16]:
# Print the column names of the DataFrame
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')

In [17]:
# Get the row indices as a list
row_indices = df.index.tolist()

# Print the list of row indices
print(row_indices)

['x', 'y', 'z', 'zz']

In [18]:
# Print information about the DataFrame
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to zz
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes
None

In [ ]:
# Generate descriptive statistics for the DataFrame
print(df.describe())

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [ ]:
# Count the number of unique values in each column
unique_counts = df.nunique()

# Print the results
print(unique_counts)

A    4
B    4
C    4
dtype: int64

In [ ]:
# Get the unique values from the 'A' column
unique_values_A = df['A'].unique()

# Print the unique values
print(unique_values_A)

[ 1  4  7 10]

In [ ]:
# Get the shape of the DataFrame (rows, columns)
shape_of_df = df.shape

# Print the shape of the DataFrame
print(shape_of_df)

(4, 3)

In [ ]:
# Get the total number of elements in the DataFrame
total_elements = df.size

# Print the total number of elements
print(total_elements)

12

In [ ]:
df

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

## Loading in Dataframes from Files

In [19]:
# Read the CSV file into a DataFrame
coffee = pd.read_csv('coffee.csv')

# Display the first few rows of the DataFrame
print(coffee.head())

# Get information about the DataFrame
print(coffee.info())

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   14 non-null     int64
dtypes: int64(1), object(2)
memory usage: 464.0+ bytes
None

## Accessing Data with Pandas

In [20]:
# Display the entire DataFrame
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [21]:
# Sample 5 random rows from the DataFrame
# with a fixed random seed for reproducibility
coffee_sample = coffee.sample(n=5, random_state=42)

# Display the sampled rows
print(coffee_sample)

          Day Coffee Type  Units Sold
9      Friday       Latte          35
11   Saturday       Latte          35
0      Monday    Espresso          25
12     Sunday    Espresso          45
5   Wednesday       Latte          25

In [ ]:
# loc
#In the context of Pandas DataFrames, loc is a powerful indexing method that allows you to select data based on labels (row and/or column names).
#coffee.loc[0] specifically selects the row with the label 0 from the DataFrame coffee.
# coffee.loc[Rows, Columns]

coffee.loc[9]

Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object

In [22]:
coffee.loc[[0,1,5]]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [23]:
coffee.loc[5:9, ["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45
9     Friday          35

#### iloc
Integer-based: Selects data based on the integer positions of the rows and columns (starting from 0).

In [24]:
# Select a subset of the 'coffee' DataFrame using integer-location based indexing.

# Select rows from index 0 (inclusive) up to, but not including, index 2.
# This effectively selects the first two rows.

# Select columns at indices 0 and 2.


# Use iloc to select the specified rows and columns.
selected_data = coffee.iloc[0:2, [0, 2] ]

print(selected_data)

      Day  Units Sold
0  Monday          25
1  Monday          15

#### Other Stuff

In [25]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [26]:
coffee.loc["Monday":"Wednesday"]

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold]
Index: []

#### Setting Values

In [27]:
coffee.loc[1:3, "Units Sold"] = 10

#### Optimized way to get single values (.at & .iat)

In [28]:
coffee.at[0,"Units Sold"]

25

In [29]:
coffee.iat[3,1]

'Latte'

#### Getting Columns

In [30]:
coffee.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [31]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

#### Sort Values

In [32]:
coffee.sort_values(["Units Sold"], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10

In [33]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10

#### Iterate over dataframe with for loop

In [34]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("Coffee Type of Row:", row["Coffee Type"])

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
Coffee Type of Row: Espresso
1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
Coffee Type of Row: Latte
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           10
Name: 2, dtype: object
Coffee Type of Row: Espresso
3
Day            Tuesday
Coffee Type      Latte
Units Sold          10
Name: 3, dtype: object
Coffee Type of Row: Latte
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
Coffee Type of Row: Espresso
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
Coffee Type of Row: Latte
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
Coffee Type of Row: Espresso
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
Coffee Type of Row: Latte
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
Coffee Type of Row: Espresso
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
Coffee Type of Row: Latte
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
Coffee Type of Row: Espresso
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
Coffee Type of Row: Latte
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
Coffee Type of Row: Espresso
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
Coffee Type of Row: Latte

## Filtering Data

In [ ]:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)

In [ ]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso        25.0   3.99       3.99
1      Monday       Latte        10.0   5.99       5.99
2     Tuesday    Espresso         NaN   3.99       3.99
3     Tuesday       Latte         NaN   5.99       5.99
4   Wednesday    Espresso        35.0   3.99       3.99
5   Wednesday       Latte        25.0   5.99       5.99
6    Thursday    Espresso        40.0   3.99       3.99
7    Thursday       Latte        30.0   5.99       5.99
8      Friday    Espresso        45.0   3.99       3.99
9      Friday       Latte        35.0   5.99       5.99
10   Saturday    Espresso        45.0   3.99       3.99
11   Saturday       Latte        35.0   5.99       5.99
12     Sunday    Espresso        45.0   3.99       3.99
13     Sunday       Latte        35.0   5.99       5.99

In [ ]:
coffee.drop(columns=['price'], inplace=True)

# the below would also have worked
# coffee = coffee.drop(columns=['price'])

In [ ]:
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new_price']]

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [ ]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        25.0       3.99    99.75
1      Monday       Latte        10.0       5.99    59.90
2     Tuesday    Espresso         NaN       3.99      NaN
3     Tuesday       Latte         NaN       5.99      NaN
4   Wednesday    Espresso        35.0       3.99   139.65
5   Wednesday       Latte        25.0       5.99   149.75
6    Thursday    Espresso        40.0       3.99   159.60
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       3.99   179.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       3.99   179.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       3.99   179.55
13     Sunday       Latte        35.0       5.99   209.65

In [ ]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [ ]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [ ]:
# Make sure to set this to your Units Sold column if you want these changes to stick
coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

0     25.00
1     10.00
2     33.75
3     33.75
4     35.00
5     25.00
6     40.00
7     30.00
8     45.00
9     35.00
10    45.00
11    35.00
12    45.00
13    35.00
Name: Units Sold, dtype: float64

In [ ]:
# coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee['Units Sold'].interpolate()

0     25.000000
1     10.000000
2     18.333333
3     26.666667
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [ ]:
coffee.dropna(subset=['Units Sold']) # Use inplace=True if you want to update the coffee df

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        10.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [ ]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        15.0   3.99    99.75
1      Monday       Latte        15.0   5.99    89.85
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [ ]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   15.000000   3.99    99.75
1      Monday       Latte   15.000000   5.99    89.85
2     Tuesday    Espresso   21.666667   3.99   119.70
3     Tuesday       Latte   28.333333   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

## Aggregating Data

#### Groupby function in Pandas

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    235.0
Latte       170.0
Name: Units Sold, dtype: float64

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    39.166667
Latte       28.333333
Name: Units Sold, dtype: float64

In [ ]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday           45.0   3.99
            Monday           25.0   3.99
            Saturday         45.0   3.99
            Sunday           45.0   3.99
            Thursday         40.0   3.99
            Tuesday           0.0   3.99
            Wednesday        35.0   3.99
Latte       Friday           35.0   5.99
            Monday           10.0   5.99
            Saturday         35.0   5.99
            Sunday           35.0   5.99
            Thursday         30.0   5.99
            Tuesday           0.0   5.99
            Wednesday        25.0   5.99

#### Pivot Tables

In [ ]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [ ]:
pivot.sum()

Coffee Type
Espresso     937.65
Latte       1018.30
dtype: float64

In [ ]:
pivot.sum(axis=1)

Day
Friday       389.20
Monday       159.65
Saturday     389.20
Sunday       389.20
Thursday     339.30
Tuesday        0.00
Wednesday    289.40
dtype: float64

In [35]:
# Handling missing values
# Explanation: Adding a missing value and handling it
df.loc[4] = ['Eve', None, None]
# Filling missing values with a default value
df.fillna(0)

<ipython-input-35-5bd3abf996d0>:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0)

      A   B   C
x     1   2   3
y     4   5   6
z     7   8   9
zz   10  11  12
4   Eve   0   0

#### Using datetime with Groupby